version: '3.8'

services:

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yml
      - /home/ubuntu/data-backup/loki:/var/lib/loki
    command: -config.file=/etc/loki/local-config.yml
    ports:
      - "3100:3100"
    restart: unless-stopped


  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitor-net
    restart: unless-stopped
