version: '3.8'

services:

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yml
      - /home/ubuntu/data-backup/loki:/var/lib/loki
    command: -config.file=/etc/loki/local-config.yml
    ports:
      - "3100:3100"
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /home/ubuntu/data-backup/promtail:/var/lib/promtail
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitor-net
    restart: unless-stopped
