version: '3.8'

networks:
  monitor-net:

services:
  prometheus-init:
    image: alpine
    container_name: prometheus-init
    command: ["sh", "-c", "chown -R 65534:65534 /prometheus"]
    volumes:
      - /home/ubuntu/data-backup/prometheus:/prometheus
    entrypoint: ""
    restart: "no"
    networks:
      - monitor-net

  grafana-init:
    image: alpine
    container_name: grafana-init
    command: ["sh", "-c", "chown -R 472:472 /var/lib/grafana"]
    volumes:
      - /home/ubuntu/data-backup/grafana:/var/lib/grafana
    entrypoint: ""
    restart: "no"
    networks:
      - monitor-net

  blackbox-init:
    image: alpine
    container_name: blackbox-init
    command: ["sh", "-c", "chown -R 65534:65534 /blackbox"]
    volumes:
      - /home/ubuntu/data-backup/blackbox:/blackbox
    entrypoint: ""
    restart: "no"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - prometheus-init
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - /home/ubuntu/data-backup/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - grafana-init
    volumes:
      - /home/ubuntu/data-backup/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitor-net
    restart: unless-stopped

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    depends_on:
      - blackbox-init
    volumes:
      - ./blackbox/config.yml:/etc/blackbox_exporter/config.yml
      - /home/ubuntu/data-backup/blackbox:/blackbox
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    ports:
      - "9115:9115"
    networks:
      - monitor-net
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yml
      - /home/ubuntu/data-backup/loki:/var/lib/loki
    command: -config.file=/etc/loki/local-config.yml
    ports:
      - "3100:3100"
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /home/ubuntu/data-backup/promtail:/var/lib/promtail
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"
    restart: unless-stopped
