version: '3.8'

services:

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitor-net
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /home/ubuntu/data-backup/promtail:/var/lib/promtail
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"
    restart: unless-stopped
